apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tryout-2020-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-tryout-2020
  template:
    metadata:
      labels:
        app: k8s-tryout-2020
    spec:
      containers:
        - name: api-container
          image: ggerritsen1/k8s-tryout-2020_api:latest
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-tryout-2020-api
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: k8s-tryout-2020
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-tryout-2020-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: api.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: k8s-tryout-2020-api
              servicePort: http
