version: '3.7'

x-base: &base
  entrypoint: modd
  command: -f ../modd.conf
  networks:
    - k8s-tryout_net
  volumes:
    - ./:/go/app

services:
  api:
    <<: *base
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        workdir: api
    environment:
      - PORT=8080
      - CUSTOMERSVC_HOSTPORT=customersvc:8081
      - GREETSVC_HOSTPORT=greetsvc:8082
    ports:
      - "8080:8080"

  customersvc:
    <<: *base
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        workdir: customersvc
    environment:
      - PORT=8081
    ports:
      - "8081:8081"

  greetsvc:
    <<: *base
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        workdir: greetsvc
    environment:
      - PORT=8082
    ports:
      - "8082:8082"

networks:
  k8s-tryout_net:
    driver: bridge
